# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Username',
            new_name='user',
        ),
        migrations.AddField(
            model_name='register',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
