# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20170619_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=25)),
                ('street_name', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=15)),
                ('district', models.CharField(choices=[['tri', 'tri'], ['ern', 'ern']], max_length=1)),
                ('state', models.CharField(choices=[['ker', 'krt'], ['tn', 'tn']], max_length=1)),
                ('phone_no', models.CharField(max_length=14)),
                ('aadhar_no', models.CharField(max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('pan_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[['elec', 'elec'], ['electrical', 'electrical']], max_length=1)),
                ('description', models.TextField()),
                ('experience', models.CharField(choices=[['amatei', 'amat'], ['pro', 'pro']], max_length=1)),
                ('pay_range', models.CharField(choices=[['100-1000', '100-1000']], max_length=1)),
                ('flexible', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='register',
            name='user',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
